import React from 'react';
import {AbsoluteFill, Series} from 'remotion';
import {DotGrid} from '../../kit/DotGrid';
import {SafeZone} from '../../kit/SafeZone';
import {W1Hook} from './scenes/personas-v8/W1Hook';
import {W2Blast} from './scenes/personas-v8/W2Blast';
import {W3AiUsers} from './scenes/personas-v8/W3AiUsers';
import {W4Question} from './scenes/personas-v8/W4Question';
import {W5KeployUsers} from './scenes/personas-v8/W5KeployUsers';
import {W6Record} from './scenes/personas-v8/W6Record';
import {W7Generate} from './scenes/personas-v8/W7Generate';
import {W8Replay} from './scenes/personas-v8/W8Replay';
import {W9Verify} from './scenes/personas-v8/W9Verify';
import {W10Payoff} from './scenes/personas-v8/W10Payoff';
import {AT} from './timelineFromAudio';

export type ReelPersonasV8Props = {safeZone?: boolean};

/**
 * "Everyone Else v8": 47.77s, 9:16. The shippable cut.
 *
 * Every scene length in this reel came out of the voiceover recording rather
 * than out of a design decision. `timelineFromAudio.ts` is generated by
 * scripts-audio-timeline.mjs, which measures where the speaker actually paused
 * and hands each scene its own line plus the pause that follows it.
 *
 * That inverts how the previous seven cuts were built. There, the timeline was
 * fixed and the script had to be trimmed to fit, which is why every VO pass
 * lost words. Here the recording is the immovable artifact and the picture
 * bends around it, so sync is a property of the build rather than something to
 * line up afterwards. Every cut lands inside a pause; none can clip a word.
 *
 * All ten scenes were re-timed by hand against the derived durations. Four
 * would otherwise have overrun: question, keployUsers, replay and verify each
 * lost between 33 and 54 frames.
 */
export const ReelPersonasV8: React.FC<ReelPersonasV8Props> = ({safeZone = false}) => (
  <AbsoluteFill>
    <DotGrid />
    <Series>
      <Series.Sequence durationInFrames={AT.hook}><W1Hook /></Series.Sequence>
      <Series.Sequence durationInFrames={AT.blast}><W2Blast /></Series.Sequence>
      <Series.Sequence durationInFrames={AT.aiUsers}><W3AiUsers /></Series.Sequence>
      <Series.Sequence durationInFrames={AT.question}><W4Question /></Series.Sequence>
      <Series.Sequence durationInFrames={AT.keployUsers}><W5KeployUsers /></Series.Sequence>
      <Series.Sequence durationInFrames={AT.record}><W6Record /></Series.Sequence>
      <Series.Sequence durationInFrames={AT.generate}><W7Generate /></Series.Sequence>
      <Series.Sequence durationInFrames={AT.replay}><W8Replay /></Series.Sequence>
      <Series.Sequence durationInFrames={AT.verify}><W9Verify /></Series.Sequence>
      <Series.Sequence durationInFrames={AT.payoff}><W10Payoff /></Series.Sequence>
    </Series>
    <SafeZone show={safeZone} />
  </AbsoluteFill>
);
