/**
 * Timeline derived from the finished voiceover, not written by hand.
 *
 * Source: audio/regressions-1.mp3 (47.79s)
 * Generated by scripts-audio-timeline.mjs. Every boundary sits inside a
 * pause in the recording, so a scene change never lands mid word and the
 * audio cannot drift against the picture.
 *
 * Regenerate rather than edit. If a beat needs longer, re-record that line.
 */
export const AT = {
  hook: 191,          // 6.37s
  blast: 177,         // 5.90s
  aiUsers: 194,       // 6.47s
  question: 72,      // 2.40s
  keployUsers: 159,   // 5.30s
  record: 153,        // 5.10s
  generate: 179,      // 5.97s
  replay: 93,        // 3.10s
  verify: 141,        // 4.70s
  payoff: 84,        // 2.80s
} as const;

export const TOTAL_FROM_AUDIO = Object.values(AT).reduce((a, b) => a + b, 0); // 1443 = 48.10s
