/**
 * Timeline derived from the finished voiceover, not written by hand.
 *
 * Source: audio/ElevenLabs_regressions.mp3 (51.53s)
 * Generated by scripts-audio-timeline.mjs. Every boundary sits inside a
 * pause in the recording, so a scene change never lands mid word and the
 * audio cannot drift against the picture.
 *
 * Regenerate rather than edit. If a beat needs longer, re-record that line.
 */
export const AT = {
  intro: 141,         // 4.70s
  hook: 165,          // 5.50s
  blast: 178,         // 5.93s
  aiUsers: 193,       // 6.43s
  question: 72,      // 2.40s
  keployUsers: 159,   // 5.30s
  record: 153,        // 5.10s
  generate: 180,      // 6.00s
  replay: 89,        // 2.97s
  verify: 142,        // 4.73s
  payoff: 83,        // 2.77s
} as const;

export const TOTAL_FROM_AUDIO = Object.values(AT).reduce((a, b) => a + b, 0); // 1555 = 51.83s
